### ISSUE TITLE
Пространство имён должно состоять из английских букв

### ISSUE THREAD

**Issue by egorpugin** [ChalovSergei/laba1-test#1]
https://github.com/ChalovSergei/laba1-test/blob/master/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BB%D0%B0%D0%B1%D0%B01/Equipment.cs#L7

**Comment by ChalovSergei** [comment]
https://github.com/ChalovSergei/laba1-test/commit/13ec762231436a2c6a9920e1dbf220c89641c291
